name: Setup R Environment and Install Packages

on:
  push:
    branches:
      - main

jobs:
  setup-r-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup R Environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

